#!/usr/bin/env python
# coding: utf-8
import chess
import glob
import re
import requests
import chess.pgn
import os
from krauss_misc import txt_mixin



# ## Goal
# 
# Read in an annotated pgn from lichess, process it, and output pdf flashcards from each relevant position.
# 
# 
# - ignore the standard lichess annotations and eval statements
#     - clean the comments before deciding if a position should be added to the pdf output
#  
# ### Step 1: Lichess PGN to markdown or something else
# 
# - is there value in markdown flashcard form?
#     - it is different than my initial FEN flashcard form, but it is a recognized standard
# 
# ### Step 2: markdown or something else to PDF via latex
# 
# - if there is no answer, the markdown approach kind of doesn't work
#     - if there isn't an answer provided, I am saying it is obvious, I guess....
#  
# ### Questions
# 
# - if I put a ? on a line by itself in the comment, should that mean the standard markdown flashcard form of question above and anser below?
# - should I output a standard text file so that generating the pdf is handled separately?
#     - I could store the text output as a list and pass it through that other code at the end
# - how do I ensure correct orientation?
#     - will I sometimes put the comments on the wrong move?


# March 2026 
url = "https://lichess.org/study/jUNlB2KL.pgn"
response = requests.get(url)
fn = "downloaded_pgn.pgn"
f = open(fn,'w')
f.write(response.text)
f.close()


black_template = r"""```chessboard
fen: %s
orientation: black
```"""

white_template = r"""```chessboard
fen: %s
orientation: white
```"""

rarrow = "→"

#pgn_files = glob.glob("*.pgn")
#pgn = open(fn)

import chess.pgn

pgn_file = open(fn, encoding="utf-8") # Open the file in text mode

games = []
while True:
    game = chess.pgn.read_game(pgn_file)
    if game is not None:
        games.append(game)
    else:
        break

# Now you can iterate through the collected games
for game in games:
    print(f"Game Event: {game.headers['Event']}")
    print(f"Result: {game.headers['Result']}")
    print(game.headers["White"])
    print(game.headers["Black"])
    # Further processing of each game can be done here
    print("-" * 20)

pgn_file.close() # Remember to close the file

#first_game = chess.pgn.read_game(pgn)
my_user_names = ['ryan49428','ryanGT','ryanGT_e4']


def find_my_side(game):
    white_user = game.headers["White"]
    if white_user in my_user_names:
        return "white"
    black_user = game.headers["Black"]
    if black_user in my_user_names:
        return "black"



def elim_eco_line(line):
    q_eco = ECO_pat.search(line)
    if q_eco is None:
        return line
    else:
        return ""


def eliminate_best_move(movein):
    out1 = best_move.sub("", movein)
    #out2 = best_move_2.sub("",out1)
    return out1


def cut_eval_change(str_in):
    test = str_in.strip()
    if rarrow not in test:
        return str_in
    else:
        ind1 = test.find("(")
        ind2 = test.find(")")
        if ind1 == 0 and ind2 > ind1:
            return test[ind2+1:]
        else:
            return test


def find_non_standard_comment(line):
    # does the comment contain anything not auto-generated by lichess/stockfish?
    # Inaccuracy|Blunder|Mistake. e5 was best.
    # Checkmate is now unavoidable.
    out00 = elim_eco_line(line)
    out0 = cut_eval_change(out00)
    out1 = get_rid_of_eval.sub('', out0)
    out1 = out1.strip()
    out2 = std_comment.sub("",out1)
    out2 = out2.strip()
    auto_phrases = ["Checkmate is now unavoidable.", "0-1 Black wins.", "1-0 White wins.", \
                   "Lost forced checkmate sequence.", "Black wins.", "White wins."]
    out3 = out2
    for phrase in auto_phrases:
        out3 = out3.replace(phrase, "")
    out4 = eliminate_best_move(out3)
    #"[a-h][1-8]"
    #Checkmate is now unavoidable. Rh2 was best. 0-1 Black wins.
    return out4

def break_comments(comment):
    answer = ''
    question = comment
    if '\n' in comment:
        mylist = comment.split('\n')
        for i, line in enumerate(mylist):
            if line.strip() == '?':
                ind = i
                question = '\n'.join(mylist[0:ind])
                answer = '\n'.join(mylist[ind+1:])
                break
    return question, answer


get_rid_of_eval = re.compile(r'\[.*eval.*?\]')
std_comment = re.compile(r"(Inaccuracy|Blunder|Mistake).*?[was best]\.")
#best_move_1 = re.compile("[BNRQK]*[a-h][1-8]")
valid_move_pat = r"[NBKRQ]?[a-h]?[1-8]?x?[a-h][1-8](=[NBKRQ])?[+#]?$|^[O0]-[O0](-[O0])?[+#]?"
best_move_pat = valid_move_pat + r" was best\."
#best_move_1 = re.compile(r"[BNRQK]x*[a-h][1-8]\+* was best\.")
#best_move_2 = re.compile(r"[a-h]x*[1-8] was best\.")
#best_move = re.compile(best_move_pat)
best_move = re.compile(r"[NBKRQ]?[a-h]?[1-8]?x?[a-h][1-8](=[NBKRQ])?[+#]? was best\.")
ECO_pat = re.compile("^[A-E]\\d+")
#eco_test = "C44 Scotch Game: Scotch Gambit, London Defense"
#ECO_pat.search(eco_test)



out_list = []
out = out_list.append
extend = out_list.extend

for game in games:
    myside = find_my_side(game)
    board = game.board()

    if myside == "white":
        template = white_template
    elif myside == "black":
        template = black_template
    else:
        raise ValueError("myside not defined")

    for node in game.mainline():
        # Print the move and its associated comment
        #print(f"Move: {node.move}, Comment: {node.comment}")
        cur_com = node.comment
        #print("cur_com:")
        #print(cur_com)
        clean_com = find_non_standard_comment(cur_com).strip()
        debug = False
        if clean_com:
            clean2 = find_non_standard_comment(clean_com)
            if debug:
                print("raw:")
                print(cur_com)
                print("clean:")
                print(clean_com)
                print("clean2:")
                print(clean2)

            if clean2:
                #print("raw:")
                #print(cur_com)
                print("clean2:")
                print(clean2)
                q,a = break_comments(clean2)
                if not a:
                    a = "no answer given"
                q = q.replace("%","\\%")
                a = a.replace("%","\\%")
                #print("question: %s" % q)
                #print("answer: %s" % a)
                out(template % board.fen())
                out(q)
                out("?")
                out(a)
                out("")
        board.push(node.move)
        # Check for specifically formatted evaluation comments
        #if node.comment and "[%eval" in node.comment:
        #    print(f"Evaluation found: {node.comment}")



fno, ext = os.path.splitext(fn)
md_out_name = fno + ".md"
txt_mixin.dump(md_out_name, out_list)

#std_com = re.compile(r"(Inaccuracy|Blunder|Mistake).*?[was best]\.")



